/*
 Navicat Oracle Data Transfer

 Source Server         : gdbaweb
 Source Server Version : 112010
 Source Host           : 27.17.3.62
 Source Schema         : PKUWH_GDBAWEB

 Target Server Version : 112010
 File Encoding         : utf-8

 Date: 03/23/2017 15:06:41 PM
*/

-- ----------------------------
--  Table structure for "SYS_MESSAGE"
-- ----------------------------
DROP TABLE "SYS_MESSAGE";
CREATE TABLE "SYS_MESSAGE" (   "MSG_ID" NUMBER(16,0) NOT NULL, "MSG_TITLE" VARCHAR2(100CHAR) NOT NULL, "MSG_CONTENT" VARCHAR2(1000CHAR), "MSG_TYPE" VARCHAR2(2CHAR) NOT NULL, "SEND_USER_IP" VARCHAR2(30CHAR) NOT NULL, "SEND_USER_ID" NUMBER(16,0) NOT NULL, "SEND_USER_NAME" VARCHAR2(30CHAR) NOT NULL, "SEND_TIME" DATE NOT NULL, "SEND_DEL_FLAG" VARCHAR2(1CHAR) NOT NULL, "RECEIVE_DEL_FLAG" VARCHAR2(1CHAR) NOT NULL, "READ_FLAG" VARCHAR2(1CHAR) NOT NULL, "RECEIVE_USER_IP" VARCHAR2(30CHAR), "RECEIVE_USER_ID" NUMBER(16,0), "RECEIVE_USER_NAME" VARCHAR2(30CHAR), "RECEIVE_TIME" DATE, "RESERVE1" VARCHAR2(100CHAR), "RESERVE2" VARCHAR2(100CHAR), "RESERVE3" VARCHAR2(100CHAR), "RESERVE4" VARCHAR2(100CHAR), "RESERVE5" VARCHAR2(100CHAR));
COMMENT ON COLUMN "SYS_MESSAGE"."MSG_ID" IS '消息编号';
COMMENT ON COLUMN "SYS_MESSAGE"."MSG_TITLE" IS '消息标题';
COMMENT ON COLUMN "SYS_MESSAGE"."MSG_CONTENT" IS '消息内容';
COMMENT ON COLUMN "SYS_MESSAGE"."MSG_TYPE" IS '消息类型';
COMMENT ON COLUMN "SYS_MESSAGE"."SEND_USER_IP" IS '发送用户IP';
COMMENT ON COLUMN "SYS_MESSAGE"."SEND_USER_ID" IS '发送用户编号';
COMMENT ON COLUMN "SYS_MESSAGE"."SEND_USER_NAME" IS '发送用户姓名';
COMMENT ON COLUMN "SYS_MESSAGE"."SEND_TIME" IS '发送时间';
COMMENT ON COLUMN "SYS_MESSAGE"."SEND_DEL_FLAG" IS '发送方删除标识';
COMMENT ON COLUMN "SYS_MESSAGE"."RECEIVE_DEL_FLAG" IS '接受方删除标识';
COMMENT ON COLUMN "SYS_MESSAGE"."READ_FLAG" IS '已读标识';
COMMENT ON COLUMN "SYS_MESSAGE"."RECEIVE_USER_IP" IS '接收用户IP';
COMMENT ON COLUMN "SYS_MESSAGE"."RECEIVE_USER_ID" IS '接收用户编号';
COMMENT ON COLUMN "SYS_MESSAGE"."RECEIVE_USER_NAME" IS '接收用户姓名';
COMMENT ON COLUMN "SYS_MESSAGE"."RECEIVE_TIME" IS '接收时间';
COMMENT ON COLUMN "SYS_MESSAGE"."RESERVE1" IS '预留字段1';
COMMENT ON COLUMN "SYS_MESSAGE"."RESERVE2" IS '预留字段2';
COMMENT ON COLUMN "SYS_MESSAGE"."RESERVE3" IS '预留字段3';
COMMENT ON COLUMN "SYS_MESSAGE"."RESERVE4" IS '预留字段4';
COMMENT ON COLUMN "SYS_MESSAGE"."RESERVE5" IS '预留字段5';

-- ----------------------------
--  Primary key structure for table "SYS_MESSAGE"
-- ----------------------------
ALTER TABLE "SYS_MESSAGE" ADD CONSTRAINT "PK_SYS_MESSAGE" PRIMARY KEY("MSG_ID");

-- ----------------------------
--  Comment for table "SYS_MESSAGE"
-- ----------------------------
COMMENT ON TABLE "SYS_MESSAGE" IS '消息表';

